// 临时：开发环境热门曲目 mock（线上接口快照），排查完骨架屏高度后删除。
import type { PopularSongsData } from "./usePopularSongs";

export const POPULAR_SONGS_MOCK: Record<"week" | "month", PopularSongsData> = {
  week: {
    range: "week",
    period_start: "2026-09-17T16:00:00Z",
    period_end: "2026-09-24T16:00:00Z",
    updated_at: "2026-09-25T07:05:00.000638696Z",
    songs: [
      {
        id: 1867,
        title: "うぇいびー",
        artist: "三枝明那",
        rank: 1,
        previous_rank: 2,
        type: "dx",
        level_index: 4,
        level: "13+",
      },
      {
        id: 1860,
        title: "MYTH Re：LEASE",
        artist: "打打だいず Vs. Tanchiky Vs. uma Vs. モリモリあつし",
        rank: 2,
        previous_rank: 1,
        type: "dx",
        level_index: 3,
        level: "14",
      },
      {
        id: 1828,
        title: "crazy (about you)",
        artist: "kamome sano",
        rank: 3,
        previous_rank: 3,
        type: "dx",
        level_index: 3,
        level: "13+",
      },
      {
        id: 1829,
        title: "Drivessover",
        artist: "Taishi",
        rank: 4,
        previous_rank: null,
        type: "dx",
        level_index: 3,
        level: "13+",
      },
      {
        id: 1863,
        title: "三日月ステップ 2023",
        artist: "r-906",
        rank: 5,
        previous_rank: 5,
        type: "dx",
        level_index: 3,
        level: "13",
      },
      {
        id: 1861,
        title: "∀",
        artist: "ああああ",
        rank: 6,
        previous_rank: 4,
        type: "dx",
        level_index: 3,
        level: "14",
      },
      {
        id: 1663,
        title: "系ぎて",
        artist: "rintaro soma",
        rank: 7,
        previous_rank: null,
        type: "dx",
        level_index: 2,
        level: "13+",
      },
      {
        id: 1842,
        title: "Synthesis.",
        artist: "tn-shi",
        rank: 8,
        previous_rank: null,
        type: "dx",
        level_index: 3,
        level: "14",
      },
      {
        id: 1868,
        title: "RED",
        artist: "三枝明那",
        rank: 9,
        previous_rank: 7,
        type: "dx",
        level_index: 3,
        level: "13",
      },
      {
        id: 1854,
        title: "超最終鬼畜妹フランドール・S",
        artist: "ビートまりお×まろん",
        rank: 10,
        previous_rank: null,
        type: "dx",
        level_index: 3,
        level: "13+",
      },
    ],
  },
  month: {
    range: "month",
    period_start: "2026-08-25T16:00:00Z",
    period_end: "2026-09-24T16:00:00Z",
    updated_at: "2026-09-25T07:05:00.000638696Z",
    songs: [
      {
        id: 1860,
        title: "MYTH Re：LEASE",
        artist: "打打だいず Vs. Tanchiky Vs. uma Vs. モリモリあつし",
        rank: 1,
        previous_rank: null,
        type: "dx",
        level_index: 3,
        level: "14",
      },
      {
        id: 1867,
        title: "うぇいびー",
        artist: "三枝明那",
        rank: 2,
        previous_rank: null,
        type: "dx",
        level_index: 4,
        level: "13+",
      },
      {
        id: 1828,
        title: "crazy (about you)",
        artist: "kamome sano",
        rank: 3,
        previous_rank: null,
        type: "dx",
        level_index: 3,
        level: "13+",
      },
      {
        id: 1861,
        title: "∀",
        artist: "ああああ",
        rank: 4,
        previous_rank: null,
        type: "dx",
        level_index: 3,
        level: "14",
      },
      {
        id: 1663,
        title: "系ぎて",
        artist: "rintaro soma",
        rank: 5,
        previous_rank: 3,
        type: "dx",
        level_index: 2,
        level: "13+",
      },
      {
        id: 1854,
        title: "超最終鬼畜妹フランドール・S",
        artist: "ビートまりお×まろん",
        rank: 6,
        previous_rank: 1,
        type: "dx",
        level_index: 2,
        level: "12+",
      },
      {
        id: 1842,
        title: "Synthesis.",
        artist: "tn-shi",
        rank: 7,
        previous_rank: 7,
        type: "dx",
        level_index: 3,
        level: "14",
      },
      {
        id: 1863,
        title: "三日月ステップ 2023",
        artist: "r-906",
        rank: 8,
        previous_rank: null,
        type: "dx",
        level_index: 3,
        level: "13",
      },
      {
        id: 1806,
        title: "Fraq",
        artist: "owl＊tree feat. べんざ",
        rank: 9,
        previous_rank: 8,
        type: "dx",
        level_index: 3,
        level: "13+",
      },
      {
        id: 799,
        title: "QZKago Requiem",
        artist: "t+pazolite",
        rank: 10,
        previous_rank: 6,
        type: "standard",
        level_index: 2,
        level: "13",
      },
    ],
  },
};
